name: "Terraform AWS Deployment"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_VERSION: "1.1.0" # Use the Terraform version required
  AWS_REGION: "us-east-1" # Set your AWS region here

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        id: init
        run: |
          cd ./
          terraform init

      - name: Terraform Plan
        id: plan
        run: |
          cd ./
          terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd ./
          terraform apply -auto-approve

      - name: Post Terraform Plan
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Terraform Plan:\n```\n${{ steps.plan.outputs.stdout }}\n```'
            });
